subconverter/urls.py
from django.conf.urls import url
# from django.contrib import admin
from converter.views import upload_file

urlpatterns = [
    url(r'^$', upload_file),
]

converter/models.py
from django.db import models

# Create your models here.

converter/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

converter/views.py
import csv
from django.http import HttpResponse
from django.shortcuts import render
from .forms import UploadFileForm
from .process import SubConverter
from os import path

def sizeof_fmt(num, suffix='B'):
    for unit in ['','Ki','Mi','Gi','Ti','Pi','Ei','Zi']:
        if abs(num) < 1024.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f%s%s" % (num, 'Yi', suffix)


def upload_file(request):
    errors = []
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            req_file = request.FILES['file']
            filesize = req_file.size
            if filesize > 300000:
                errors.append(sizeof_fmt(filesize) + ' is too big of a file')
            else:
                resultlines = SubConverter(req_file)
                if not resultlines:
                    errors.append('Failed to process the file. Wrong format?')
                if resultlines:
                    response_content = '\r\n'.join(resultlines)
                    response = HttpResponse(response_content, content_type='text/plain')
                    req_file_name = path.splitext(req_file.name)[0]
                    req_file_name = req_file_name.replace(' ', '_')
                    disp_str = 'attachment; filename="%s.srt"' % req_file_name
                    response['Content-Disposition'] = disp_str
                    return response
    else:
        form = UploadFileForm()
    return render(request, 'converter/upload.html', {'form': form, 'errors': errors})

converter/templates/converter/upload.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link href="{% static "converter/style.css" %}" rel="stylesheet" type="text/css">
	<title></title>
</head>
<body>
	<div id="wrapper">
	<main>
	<div id="upload"><span>SAMI-to-SRT converter</span></div>
	{% if form %}
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<p><label for="id_file" id="filename1"><span id="txt">Select a file</span></label></p>
		<input type="submit" value="Upload" id="submit-btn"/>
	</form>
	{% endif %}
	{% if errors %}
	{% for error in errors %}
	<p class="error" id="tem-error"><span class="error">{{ error }}</span></p>
	{% endfor %}
	{% endif %}
	<p id="ejs"><span id="span-ejs" class="error"></span></p>
	</main>
	</div>
	<script src="{% static "converter/script.js" %}"></script>
</body>
</html>